SELECT 
	v.ID_PESSOA, 
	COUNT(ID_VENDA)
FROM f_Vendas AS v;
	INNER JOIN d_Pessoa AS p WITH(NOLOCK) ON v.ID_PESSOA = p.ID_PESSOA
	INNER JOIN d_Tempo AS t WITH(NOLOCK) ON v.ID_TEMPO = t.ID_TEMPO
WHERE t.DT_REF >= '2020-03-01'
  AND t.DT_REF <= '2020-03-31'
GROUP BY
	v.ID_PESSOA;